spring:
  application:
    name: talkandpokefrontapi1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true
  instance:
    preferIpAddress: true
    ip-address: localhost

server:
  port: 8181